# Generated by Django 5.2.1 on 2025-06-13 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0005_alter_message_sender_alter_messagehistory_edited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='parental_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='chats.message'),
        ),
    ]
