apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
    version: blue # start by pointing to blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
